higss/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('portal.urls'))
]

admin.site.site_header = 'HIGSS Portal'
admin.site.site_title =  'HIGSS Portal'

portal/urls.py
from django.urls import path
from .views import apply, SignUp,status, pay, pay_fee, confirm, success, fees


urlpatterns = [
    path('admissions/', apply),
    path('pay/<email>/<pk>', pay, name='pay'),
    path('pay_fee/<email>/<pk>/<fee>', pay_fee, name='pay_fee'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('status/<pk>/',status, name='status'),
    path('confirm/', confirm, name='confirm'),
    path('fees/', fees, name='fees'),
    path('success/', success, name='success'),
]

portal/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User

GENDER_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female')
)

CLASS_CHOICES = (
   ('JSS1', 'JSS1'),
   ('JSS2', 'JSS2'),
   ('JSS3', 'JSS3'),
   ('SSS1', 'SSS1'),
   ('SSS2', 'SSS2'),
   ('SSS3', 'SSS3')
)

RELATIONSHIP_CHOICES = (
    ('Father', 'Father'),
    ('Mother', 'Mother'),
    ('Guardian', 'Guardian')
)

class Application(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(help_text='Enter email address')
    timestamp = models.DateTimeField()
    passport = models.ImageField(upload_to='passports/', blank=True, null=True)
    surname_of_pupil = models.CharField(max_length=255, help_text='Enter Surname of pupil')
    firstname_of_pupil = models.CharField(max_length=255, help_text='Enter First Name of pupil')
    othername_of_pupil = models.CharField(max_length=255, help_text='Enter Middle Name of pupil', null=True, blank=True)
    sex = models.CharField(choices=GENDER_CHOICES, max_length=128)
    date_of_birth = models.DateField()
    class_applying_to = models.CharField(choices=CLASS_CHOICES, max_length=128)
    full_name_of_guardian = models.CharField(max_length=50)
    relationship_with_pupil = models.CharField(choices=RELATIONSHIP_CHOICES, max_length=128)
    profession = models.CharField(max_length=50)
    residential_address = models.CharField(max_length=50)
    office_address = models.CharField(max_length=50)
    telephone = models.CharField(max_length=50)
    child_aliments = models.TextField(help_text='Does the child have any persistent aliments?')
    confirm = models.BooleanField(default=False)
    admission_number = models.CharField(null=True, blank=True, max_length=50)
    school_fees = models.CharField(null=True, blank=True, max_length=50)

    def __str__(self):
        return self.surname_of_pupil +' '+ self.firstname_of_pupil

portal/forms.py
from django.forms import ModelForm,DateField,DateInput,FileInput
from django import forms
from .models import Application
from django.utils.translation import ugettext_lazy as _

class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = '__all__'
        widgets = {
            'date_of_birth':DateInput(attrs={'type':'date','class':'datetimepicker-dummy-input','readonly':'readonly'}),
            'passport':FileInput(attrs={'class':'file-input'})
        }
        labels = {
            'passport':_("Pupil's Picture &nbsp;&nbsp;&nbsp;"),
            'firstname_of_pupil':_("First Name of Pupil"),
            'surname_of_pupil':_("Surname of Pupil"),
            'othername_of_pupil':_("Middle Name of Pupil"),
            'sex':_("Gender"),
            'date_of_birth':_("Date of Birth"),
            'class_applying_to':_("Class Applying to"),
            'full_name_of_guardian':_("Full Name of Sponsor"),
            'relationship_with_pupil':_("Relationship with Pupil")
        }

        exclude = ('user', 'passed', 'timestamp', 'admission_number')

class CheckForm(forms.Form):
    admission_number = forms.CharField(max_length=50)

portal/views.py
from django.shortcuts import render, redirect
from django import forms
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .models import Application
from .forms import ApplicationForm, CheckForm
from django.http import HttpResponse

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def apply(request):
    applications = Application.objects.all()
    if request.method == "POST":
        form = ApplicationForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            url = '/status/{}/'.format(model_instance.id)
            return redirect(url, {'result_data':model_instance })
 
    else:
 
        form = ApplicationForm()
    return render(request, 'home.html', {'form': form, 'applications': applications})

def status(request, pk):
    application = Application.objects.get(id=pk)
    if request.method == "POST":
        form = ApplicationForm(request.POST, instance=application)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return render(request, 'status.html', {'form': form, 'pk': pk})
 
    else:
 
        form = ApplicationForm(instance=application)
    return render(request, 'status.html', {'form': form, 'pk': pk})

def pay(request, email, pk):
    redirect_url = '/confirm/'
    return render(request, 'pay.html', {'email': email, 'redirect_url': redirect_url})

def success(request):
    return render(request, 'success.html', {})

def pay_fee(request, pk, email, fee):
    amount = int(fee) * 100 
    redirect_url = '/success/'
    return render(request, 'pay_fees.html', {'email': email, 'redirect_url': redirect_url, 'amount': amount})

def fees(request):
    application = None
    if request.method == "POST":
        form = CheckForm(request.POST)
        if form.is_valid():
            try:
                application=Application.objects.get(admission_number=form.cleaned_data['admission_number'])
            except Application.DoesNotExist:
                application = None

    else:
        form = CheckForm()
    return render(request, 'school_fees.html', {'form': form, 'application': application})

def confirm(request):
    return render(request, 'confirm.html', {})

portal/templates/applicationDetails.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
	<section class="hero is-primary" style="background:#3F51B5;">
		<div class="hero-body">
			<div class="container">
			 <img src="{% static "images/logo.png" %}" alt="logo.png" style=" display:block; margin: 0 auto; width: 200px;"/>
      <br>
				<h1 class="title" style="text-align: center;">
					Application Fee
				</h1>
				<br>
				<h2 class="subtitle" style="text-align: center;">
					Confirm Details and pay application fee
				</h2>
				<br><br>
				<a class="button is-primary is-inverted is-outlined" href="{% url 'logout' %}" style="display: block; width: 20%; margin: 0 auto; min-width: 200px;">Logout</a>
			</div>
		</div>
	</section>

	<br><br><br>

	<div class="container" style="width: 50%; min-width: 200px; max-width: 500px;">

		<label class="label has-text-grey-lighter">Passport Photograph</label>

		<br>


		<label class="label has-text-grey-lighter">Full name of pupil:</label>
		<h2 class="title is-3">Faruk Shuaibu Adamu</h2>
  
		
		<label class="label has-text-grey-lighter">Sex:</label>
		<h2 class="title is-3">Male</h2>
  
		   
		<label class="label has-text-grey-lighter">Date of Birth</label>
		<h2 class="title is-3">23/10/1996</h2>
  
			 
		<label class="label has-text-grey-lighter">Class you are applying to</label>
		<h2 class="title is-3">SSS3</h2>
  
		<label class="label has-text-grey-lighter">Fullname of parent/guardian</label>
		<h2 class="title is-3">Shuaibu Adamu</h2>
  
		<label class="label has-text-grey-lighter">Relationship with pupil</label>
		<h2 class="title is-3">Father</h2>
  
		<label class="label has-text-grey-lighter">Profession/Occupation</label>
		<h2 class="title is-3">Diesel Mechanic </h2>
  
		<label class="label has-text-grey-lighter">Residential Address</label>
		<h2 class="title is-3">GP 484 Suleiman Crescent Kano Nigeria.</h2>
  
		<label class="label has-text-grey-lighter">Office Address</label>
		<h2 class="title is-3">No. 2 Batwa Close Hadeja Road Kano.</h2>
  
		<label class="label has-text-grey-lighter">Telephone 1</label>
		<h2 class="title is-3">+2348176836670</h2>
  
		<label class="label has-text-grey-lighter">Does the child have any persistent aliments?</label>
		<h2 class="title is-3">No</h2>
		<br><br>
		<div class="field is-grouped" style="margin: 0 auto; width: 100%;">
			<div class="control"  style="margin: 0 auto; width: 100%;">
				<a href="{% url 'registration:registration' %}" style="display: inline-block; width: 45%; min-width: 200px; margin-top: 20px;"><button class="button is-warning" style="width: 100%;">Go back</button> </a>

				<a href="{% url 'account:dashboard' %}" style="display: inline-block; width: 45%; min-width: 200px; margin-top: 20px;" ><button class="button is-link" style="width: 100%;" onclick="payWithPaystack();">Pay Fee : &#x20A6; 1000</button></a>
			</div>
		</div>

		<br><br><br><br>


		<br><br><br><br>

	</div>




{% endblock %}

portal/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
  {% load static%}
  
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}HIGSS Portal{% endblock %}</title>
  <link rel="manifest" href="{% static 'site.webmanifest' %}">
	<link rel="apple-touch-icon" href="icon.png">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@6/dist/css/bulma-calendar.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bulma-calendar@6/dist/js/bulma-calendar.min.js"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>


	<style>
		 #hint_id_username, #hint_id_password1 {
         display: none;
     }
	</style>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.4.1.min.js"><\/script>')</script>
{#<script src="js/plugins.js"></script>#}
{#<script src="js/main.js"></script>#}

<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
<script>
window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
ga('create', 'UA-XXXXX-Y', 'auto'); ga('set', 'transport', 'beacon'); ga('send', 'pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async></script>
<script>
// Initialize all input of type date
var calendars = bulmaCalendar.attach('[type="date"]');

// Loop on each calendar initialized
for (var i = 0; i < calendars.length; i++) {
// Add listener to date:selected event
calendars[i].on('select', date => {
console.log(date);
});
}

// To access to bulmaCalendar instance of an element
var element = document.querySelector('#id_date_of_birth');
if (element) {
// bulmaCalendar instance is available as element.bulmaCalendar
element.bulmaCalendar.on('select', function (datepicker) {
console.log(datepicker.data.value());
});
}
</script>

</body>
</html>

portal/templates/confirm.html
{% extends 'base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block title %}Confirmation - Hassan Ibrahim Gwarzo Secondary Schools {% endblock %}

{% block content %}
<section class="hero is-primary"  style="background:#3F51B5;">
    <div class="hero-body">
      <div class="container">
        <img src="{% static "images/logo.png" %}" alt="logo.png" style=" display:block; margin: 0 auto; width: 200px;"/>
        <h1 class="title" style="text-align: center;">
        Admission Payment Successful         
        </h1>
        <br>
        <h2 class="subtitle" style="text-align: center;">
        </h2>
        <p style="text-align: center;">We have received your payment.</p>
        <br><br>
        <h4 class="subtitle" style="text-align: center;">We shall send the details of the entrance test to your email. </h4> 
        <h4 class="subtitle" style="text-align: center;">Thank you for applying to Hassan Ibrahim Gwarzo Secondary Schools(HIGSS).</h4> 

        <p class="subtitle" style="text-align: center;">For any enquiries kindly contact us at:  </p>
        <p class="subtitle" style="text-align: center;">08030000000</p>
        <a href="https://www.higss.sch.ng" style="display: block; text-align: center; margin: 0 auto;" type="submit" class="btn btn-success" >Return to HIGSS Website </a>
        <br>
      </div>
    </div>
  </section>
{% endblock %}

portal/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block title %}New Admission - Hassan Ibrahim Gwarzo Secondary Schools{% endblock %}

{% block content %}
<section class="hero is-primary"  style="background:#3F51B5;">
    <div class="hero-body">
      <div class="container">
          <img src="{% static "images/logo.png" %}" alt="logo.png" style=" display:block; margin: 0 auto; width: 200px;"/>
        <h1 class="title" style="text-align: center;">
          HIGSS Admission
        </h1>
        <br>
        <h2 class="subtitle" style="text-align: center;">
            Welcome to your HIGSS new admission portal
        </h2>
      </div>
    </div>
  </section>

  <br><br><br>
 
  <div class="container" style="width: 50%; min-width: 200px; max-width: 500px;">
      <h4 class="title"> Submit a new application </h4>
      <form method="post" >
          {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            
        {% csrf_token %}
  
        <div class="form-group col-md-12 mb-0">
        <div class="file has-name">
          <label class="file-label">
            {{ form.passport|as_crispy_field }}
            <span class="file-cta">
              <span class="file-icon">
                <svg class="svg-inline--fa fa-upload fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="upload" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M296 384h-80c-13.3 0-24-10.7-24-24V192h-87.7c-17.8 0-26.7-21.5-14.1-34.1L242.3 5.7c7.5-7.5 19.8-7.5 27.3 0l152.2 152.2c12.6 12.6 3.7 34.1-14.1 34.1H320v168c0 13.3-10.7 24-24 24zm216-8v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h136v8c0 30.9 25.1 56 56 56h80c30.9 0 56-25.1 56-56v-8h136c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"></path></svg><!-- <i class="fas fa-upload"></i> -->
              </span>
              <span class="file-label">
                Choose a file…
              </span>
            </span>
            <span class="file-name">
              yourphoto.png
            </span>
          </label>
        </div>
        </div>
       
        <div class="form-group col-md-12 mb-0">
          {{ form.email|as_crispy_field }}
        </div>
     
  
        <div class="form-group col-md-12 mb-0">
          {{ form.surname_of_pupil|as_crispy_field }}
        </div>

        <div class="form-group col-md-12 mb-0">
          {{ form.firstname_of_pupil|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.othername_of_pupil|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
          {{ form.sex|as_crispy_field }}
        </div>
      
    
  
        <div class="form-group col-md-12 mb-0">
          {{ form.date_of_birth|as_crispy_field }}
        </div>
      
        <div class="form-group col-md-12 mb-0">
          {{ form.class_applying_to|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.full_name_of_guardian|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.relationship_with_pupil|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.profession|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.residential_address|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.office_address|as_crispy_field }}
        </div>
  
        <div class="form-group col-md-12 mb-0">
          {{ form.telephone|as_crispy_field }}
        </div>
  
   
        <div class="form-group col-md-12 mb-0">
          {{ form.child_aliments|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0"></div>
        <center><button style="width: 90%" type="submit" class="btn btn-success" >Proceed</button></center>
        <br> <br>
      </form>
  
  </div>

{% endblock %}

portal/templates/pay.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Make Payment</title>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        function payWithPaystack() {
            var amount = 10250;
            var handler = PaystackPop.setup({
                key: 'pk_live_177c86f95fae13e27d2ceab795e1f710b8b7fe55',
                email: "{{ email }}",
                amount: amount * 100,
                currency: "NGN",
                ref: '' + Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                metadata: {
                    custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "+2348012345678"
                        }
                    ]
                },
                callback: function (response) {
                    window.location.href = "{{redirect_url}}"
                },
                onClose: function () {
                    // alert('window closed');
                }
            });
            handler.openIframe();
        };
    </script>
</head>


<body onload="payWithPaystack();">


</body>

</html>

portal/templates/pay_fees.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Make Payment</title>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        function payWithPaystack() {
            var handler = PaystackPop.setup({
                key: 'pk_live_177c86f95fae13e27d2ceab795e1f710b8b7fe55',
                email: "{{ email }}",
                amount: "{{ amount }}",
                currency: "NGN",
                ref: '' + Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                metadata: {
                    custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "+2348012345678"
                        }
                    ]
                },
                callback: function (response) {
                    window.location.href = "{{redirect_url}}"
                },
                onClose: function () {
                    // alert('window closed');
                }
            });
            handler.openIframe();
        };
    </script>
</head>


<body onload="payWithPaystack();">


</body>

</html>

portal/templates/payme.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Payment</title>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        function payWithPaystack() {
            var amount = 1000;
            var handler = PaystackPop.setup({
                key: 'pk_test_3ffa7fee625fe7dd52aa8a24cb4a6f8e7c4fa16f',
                email: "anasbalarabe@gmail.com",
                amount: amount * 100,
                currency: "NGN",
                ref: '' + Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                metadata: {
                    custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "+2348012345678"
                        }
                    ]
                },
                callback: function (response) {
                    // alert('success. transaction ref is ' + response.reference);
                },
                onClose: function () {
                    // alert('window closed');
                }
            });
            handler.openIframe();
        };
    </script>
</head>


<body onload="payWithPaystack();">


</body>

</html>

portal/templates/school_fees.html
{% extends 'base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block title %}School Fees Payment – Hassan Ibrahim Gwarzo Secondary Schools{% endblock %}

{% block content %}
<section class="hero is-primary"  style="background:#3F51B5;">
    <div class="hero-body">
      <div class="container">
          <img src="{% static "images/logo.png" %}" alt="logo.png" style=" display:block; margin: 0 auto; width: 200px;"/>
        <h1 class="title" style="text-align: center;">
            HIGSS School Fees Payment          
        </h1>
        <br>
        <h2 class="subtitle" style="text-align: center;">
        </h2>
        <p style="text-align: center;">Enter the admission number sent to your email in the field provided below to retrieve your pupil’s details.</p>
        <br><br>
        <br>
        {% if application.admission_number %}
        <h4 class="subtitle" style="text-align: center;"> Pupil Name: {{application.surname_of_pupil}} {{application.first_of_pupil}}</h4> 
        <h4 class="subtitle" style="text-align: center;"> Admission Number: {{application.admission_number}}</h4> 
        <h4 class="subtitle" style="text-align: center;"> School Fees: {{application.school_fees}}</h4> 
        <br>
        <p class="subtitle" style="text-align: center;"> 
        <a href="{% url 'pay_fee' email=application.email pk=application.id fee=application.school_fees %}" class="btn btn-success" class="subtitle" style="text-align: center;" >Pay School Fees</a>
        </p>
        {% else %}
        <form method="post" >
            {% csrf_token %}
                <div class="form-group col-md-12 mb-0">
                    {{ form.admission_number|as_crispy_field }}
                  </div>
                  <div class="form-group col-md-12 mb-0">
                  <button style="text-align: center;" type="submit" class="btn btn-success" >Proceed</button>
                  </div>
            </form> <br> <br>
        {% endif %}    


        <br>
      </div>
    </div>
  </section>
{% endblock %}

portal/templates/signup.html
{% extends 'base.html' %}
{% load static%}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<section class="hero is-primary" style="background:#fff;">
		<div class="hero-body">
			<div class="container">

			<img src="{% static "images/logo.png" %}" alt="F84xZ.png" style="background:#fff; display:block; margin: 0 auto; width: 200px;"/>


				<h1 class="title" style="text-align: center; color:#3F51B5;">
					Create an account
				</h1>
				<h2 class="subtitle" style="text-align: center; color:#3F51B5;">
					Create an account to login and apply.
				</h2>
			</div>
		</div>
	</section>
	
	<br>
	<div class="container" style="width: 50%; min-width: 200px; max-width: 500px;">
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign up</button>
  </form>
  <br>
		<div class="control">
			<a href="{% url 'login' %}"><button class="button is-text">Go to Login</button></a>
		</div>
	</div>

{% endblock %}

portal/templates/success.html
{% extends 'base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block title %}School Fees Confirmation - Hassan Ibrahim Gwarzo Secondary Schools {% endblock %}

{% block content %}
<section class="hero is-primary"  style="background:#3F51B5;">
    <div class="hero-body">
      <div class="container">
        <img src="{% static "images/logo.png" %}" alt="logo.png" style=" display:block; margin: 0 auto; width: 200px;"/>
        <h1 class="title" style="text-align: center;">
        School Fees Payment Successful         
        </h1>
        <br>
        <h2 class="subtitle" style="text-align: center;">
        </h2>
        <p style="text-align: center;">We have received your payment.</p>
        <br><br>
        <p class="subtitle" style="text-align: center;">For any enquiries kindly contact us at:  </p>
        <p class="subtitle" style="text-align: center;">08030000000</p>


        <a href="https://www.higss.sch.ng" style="display: block; text-align: center; margin: 0 auto;" type="submit" class="btn btn-success" >Return to HIGSS Website</a>
        <br>
      </div>
    </div>
  </section>
{% endblock %}